import type { ThemeConfig } from "./types";

export const threadColor: ThemeConfig = {
  id: "thread-color",
  name: "Colour Thread",
  family: "minimal-thread",
  layout: "thread",
  fonts: {
    primary: "'IBM Plex Sans', -apple-system, sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  googleFontsUrl:
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500&family=IBM+Plex+Mono:wght@400&display=swap",
  maxWidth: 560,
  threadWidth: 1,
  threadPaddingLeft: 28,
  dotSize: 7,
  messageSpacing: 32,
  lineHeight: 1.7,
  userFontWeight: 400,
  aiFontWeight: 300,
  labelFontSize: 11,
  labelFontWeight: 500,
  labelLetterSpacing: "0.08em",
  labelUppercase: true,
  light: {
    accentUser: "#6b8fad",
    accentAi: "#6ba880",
    threadColor: "#e0e0e0",
    dotUser: "#6b8fad",
    dotAi: "#6ba880",
    threadUser: "#b0c8da",
    threadAi: "#a8d0b4",
    textPrimary: "#111",
    textSecondary: "#444",
    labelUser: "#6b8fad",
    labelAi: "#6ba880",
    codeBg: "#f3f3f3",
    codeColor: "#555",
    codeBlockBg: "#f5f5f5",
    codeBlockColor: "#555",
    sectionMark: "#ccc",
  },
  dark: {
    accentUser: "#6b8fad",
    accentAi: "#6ba880",
    threadColor: "#2a2a2a",
    dotUser: "#6b8fad",
    dotAi: "#6ba880",
    threadUser: "#2e3e4a",
    threadAi: "#2a3e30",
    textPrimary: "#e0e0e0",
    textSecondary: "#a8a8a8",
    labelUser: "#7a9ec2",
    labelAi: "#7ab88e",
    codeBg: "rgba(255,255,255,0.06)",
    codeColor: "#c8b89a",
    codeBlockBg: "#222",
    codeBlockColor: "#888",
    sectionMark: "#333",
  },
};
