import type { ThemeConfig } from "./types";

export const threadBold: ThemeConfig = {
  id: "thread-bold",
  name: "Bold Markers",
  family: "minimal-thread",
  layout: "thread",
  fonts: {
    primary: "'IBM Plex Sans', -apple-system, sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  googleFontsUrl:
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400&display=swap",
  maxWidth: 560,
  threadWidth: 2,
  threadPaddingLeft: 32,
  dotSize: 10,
  messageSpacing: 32,
  lineHeight: 1.7,
  userFontWeight: 500,
  aiFontWeight: 400,
  labelFontSize: 12,
  labelFontWeight: 600,
  labelLetterSpacing: "0.06em",
  labelUppercase: true,
  light: {
    accentUser: "#555",
    accentAi: "#999",
    threadColor: "#ccc",
    dotUser: "#555",
    dotAi: "#999",
    textPrimary: "#111",
    textSecondary: "#333",
    labelColor: "#777",
    codeBg: "#f0f0f0",
    codeColor: "#444",
    codeBlockBg: "#f2f2f2",
    codeBlockColor: "#444",
    sectionMark: "#bbb",
  },
  dark: {
    accentUser: "#c0c0c0",
    accentAi: "#888",
    threadColor: "#3a3a3a",
    dotUser: "#c0c0c0",
    dotAi: "#888",
    textPrimary: "#e8e8e8",
    textSecondary: "#b8b8b8",
    labelColor: "#777",
    codeBg: "rgba(255,255,255,0.08)",
    codeColor: "#c8b89a",
    codeBlockBg: "#242424",
    codeBlockColor: "#999",
    sectionMark: "#444",
  },
};
