import type { ThemeConfig } from "./types";

export const threadWideMargin: ThemeConfig = {
  id: "thread-wide-margin",
  name: "Wide Margin",
  family: "minimal-thread",
  layout: "wide-margin",
  fonts: {
    primary: "'IBM Plex Sans', -apple-system, sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  googleFontsUrl:
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500&family=IBM+Plex+Mono:wght@400&display=swap",
  maxWidth: 680,
  threadWidth: 1,
  dotSize: 7,
  messageSpacing: 32,
  lineHeight: 1.7,
  userFontWeight: 400,
  aiFontWeight: 300,
  labelFontSize: 11,
  labelFontWeight: 500,
  labelLetterSpacing: "0.08em",
  labelUppercase: true,
  light: {
    accentUser: "#888",
    accentAi: "#bbb",
    threadColor: "#ddd",
    dotUser: "#888",
    dotAi: "#bbb",
    textPrimary: "#111",
    textSecondary: "#444",
    labelColor: "#888",
    marginLabel: "#999",
    codeBg: "#f3f3f3",
    codeColor: "#555",
    codeBlockBg: "#f5f5f5",
    codeBlockColor: "#555",
    sectionMark: "#ccc",
  },
  dark: {
    accentUser: "#7a9ec2",
    accentAi: "#7ab88e",
    threadColor: "#333",
    dotUser: "#7a9ec2",
    dotAi: "#7ab88e",
    textPrimary: "#e0e0e0",
    textSecondary: "#a8a8a8",
    labelColor: "#666",
    marginLabel: "#555",
    codeBg: "rgba(255,255,255,0.06)",
    codeColor: "#c8b89a",
    codeBlockBg: "#222",
    codeBlockColor: "#888",
    sectionMark: "#333",
  },
};
