import type { ThemeConfig } from "./types";

export const threadFineLine: ThemeConfig = {
  id: "thread-fine-line",
  name: "Fine Line",
  family: "minimal-thread",
  layout: "thread",
  fonts: {
    primary: "'IBM Plex Sans', -apple-system, sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  googleFontsUrl:
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500&family=IBM+Plex+Mono:wght@400&display=swap",
  maxWidth: 560,
  threadWidth: 0.5,
  threadPaddingLeft: 28,
  dotSize: 5,
  messageSpacing: 40,
  lineHeight: 1.7,
  userFontWeight: 400,
  aiFontWeight: 300,
  labelFontSize: 10,
  labelFontWeight: 500,
  labelLetterSpacing: "0.1em",
  labelUppercase: true,
  light: {
    accentUser: "#999",
    accentAi: "#ccc",
    threadColor: "#e0e0e0",
    dotUser: "#999",
    dotAi: "#ccc",
    textPrimary: "#111",
    textSecondary: "#555",
    labelColor: "#aaa",
    codeBg: "#f3f3f3",
    codeColor: "#555",
    codeBlockBg: "#f5f5f5",
    codeBlockColor: "#555",
    sectionMark: "#ddd",
  },
  dark: {
    accentUser: "#7a9ec2",
    accentAi: "#7ab88e",
    threadColor: "#2e2e2e",
    dotUser: "#7a9ec2",
    dotAi: "#7ab88e",
    textPrimary: "#e0e0e0",
    textSecondary: "#a0a0a0",
    labelColor: "#666",
    codeBg: "rgba(255,255,255,0.06)",
    codeColor: "#b8a888",
    codeBlockBg: "#222",
    codeBlockColor: "#888",
    sectionMark: "#333",
  },
};
