import type { ThemeConfig } from "./types";

export const threadSerif: ThemeConfig = {
  id: "thread-serif",
  name: "Serif",
  family: "minimal-thread",
  layout: "thread",
  fonts: {
    primary: "'Literata', Georgia, serif",
    label: "'IBM Plex Sans', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  googleFontsUrl:
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500&family=IBM+Plex+Mono:wght@400&family=Literata:opsz,wght@7..72,300;7..72,400;7..72,500&display=swap",
  maxWidth: 560,
  threadWidth: 1,
  threadPaddingLeft: 28,
  dotSize: 7,
  messageSpacing: 36,
  lineHeight: 1.8,
  userFontWeight: 400,
  aiFontWeight: 300,
  labelFontSize: 11,
  labelFontWeight: 500,
  labelLetterSpacing: "0.08em",
  labelUppercase: true,
  light: {
    accentUser: "#888",
    accentAi: "#bbb",
    threadColor: "#ddd",
    dotUser: "#888",
    dotAi: "#bbb",
    textPrimary: "#1a1a1a",
    textSecondary: "#444",
    labelColor: "#999",
    codeBg: "#f3f3f3",
    codeColor: "#555",
    codeBlockBg: "#f5f5f5",
    codeBlockColor: "#555",
    sectionMark: "#ccc",
  },
  dark: {
    accentUser: "#7a9ec2",
    accentAi: "#7ab88e",
    threadColor: "#333",
    dotUser: "#7a9ec2",
    dotAi: "#7ab88e",
    textPrimary: "#e0e0e0",
    textSecondary: "#b0b0b0",
    labelColor: "#666",
    codeBg: "rgba(255,255,255,0.06)",
    codeColor: "#c8b89a",
    codeBlockBg: "#222",
    codeBlockColor: "#999",
    sectionMark: "#444",
  },
};
